"""empty message

Revision ID: 23ac0d544bb9
Revises: 
Create Date: 2020-12-21 23:59:37.017448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23ac0d544bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.TIMESTAMP(), nullable=False),
    sa.Column('stoptime', sa.TIMESTAMP(), nullable=False),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_name', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.drop_table('divvy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy',
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starttime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stoptime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bikeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_station_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_station_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('usertype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trip_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trip_id', name='divvy_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
